name: 'Prisma'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  prisma-schema:
    name: 'Validate prisma schema'
    uses: technology-studio/github-workflows/.github/workflows/_prisma.yml@main
    secrets: inherit
